
language: cpp
os: linux
services:
  - xvfb
addons:
  apt:
    packages:
    - xorg-dev
    - ninja-build
    - libgl1-mesa-dev
matrix:
  include:
    - compiler: gcc
    - compiler: clang
before_script: mkdir build && cd build
script: cmake .. -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_SHARED_LIBS=True -DBUILD_ALL_TESTS=True -DMINSG_RECOMMENDED_EXT=True -DCMAKE_CXX_FLAGS="-Wall -Wextra -pedantic -Wno-inconsistent-missing-override -Wno-unused-parameter -Wno-unused-variable" && ninja && xvfb-run ctest --verbose -D ExperimentalTest -E "SphericalSamplingSerialization|ValuatedRegionNode"

